definitions:
  common.MetaData:
    properties:
      links:
        items:
          additionalProperties:
            type: string
          type: object
        type: array
      page:
        type: integer
      page_count:
        type: integer
      per_page:
        type: integer
      total_count:
        type: integer
    type: object
  common.ResponseDTO:
    properties:
      _metadata:
        $ref: '#/definitions/common.MetaData'
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: api-service  API
  title: api-service API
paths:
  /api/v1/applications:
    get:
      description: Get all applications
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get all applications
      tags:
      - Application
    post:
      consumes:
      - application/json
      description: Update Application by company id and  repository id
      parameters:
      - description: ApplicationWithUpdateOption Data
        in: body
        name: data
        required: true
        schema:
          type: object
      - description: repository Id
        in: query
        name: repositoryId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Update Application
      tags:
      - Application
  /api/v1/applications/{id}:
    get:
      description: Get application by appliction id
      parameters:
      - description: application id
        in: path
        name: id
        required: true
        type: string
      - description: repository id
        in: query
        name: repositoryId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get application by appliction id
      tags:
      - Application
  /api/v1/bitbuckets/branches:
    get:
      description: Gets Branches
      parameters:
      - description: User Name
        in: query
        name: userName
        required: true
        type: string
      - description: Repository Id
        in: query
        name: repoId
        required: true
        type: string
      - description: Repository Name
        in: query
        name: repoName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get Branches
      tags:
      - Bitbucket
  /api/v1/bitbuckets/commits:
    get:
      description: "Gets \tCommit By Branch"
      parameters:
      - description: User Name
        in: query
        name: userName
        required: true
        type: string
      - description: Repository Id
        in: query
        name: repoId
        required: true
        type: string
      - description: Repository Name
        in: query
        name: repoName
        required: true
        type: string
      - description: Branch
        in: query
        name: branch
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get Commit By Branch
      tags:
      - bitbucket
  /api/v1/bitbuckets/webhooks:
    delete:
      description: Disable Webhook
      parameters:
      - description: User Name
        in: query
        name: userName
        required: true
        type: string
      - description: Repository Id
        in: query
        name: repoId
        required: true
        type: string
      - description: Repository Name
        in: query
        name: repoName
        required: true
        type: string
      - description: Webhook Id
        in: query
        name: webhookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Disable Webhook
      tags:
      - bitbucket
    put:
      description: Enable Webhook
      parameters:
      - description: User Name
        in: query
        name: userName
        required: true
        type: string
      - description: Repository Id
        in: query
        name: repoId
        required: true
        type: string
      - description: Repository Name
        in: query
        name: repoName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Enable Webhook
      tags:
      - bitbucket
  /api/v1/companies:
    get:
      description: Gets companies
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Record count
        in: query
        name: limit
        type: integer
      - description: Loads Repositories
        in: query
        name: loadRepositories
        type: boolean
      - description: Loads Applications
        in: query
        name: loadApplications
        type: boolean
      - description: status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get companies
      tags:
      - Company
    post:
      description: Saves company
      parameters:
      - description: Company data
        in: body
        name: data
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Save company
      tags:
      - Company
  /api/v1/companies/{id}:
    get:
      description: Gets company by id
      parameters:
      - description: Company id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get company by id
      tags:
      - Company
  /api/v1/companies/{id}/applications:
    get:
      description: Gets RApplications by company id and repository type
      parameters:
      - description: Company id
        in: path
        name: id
        required: true
        type: string
      - description: status
        in: query
        name: status
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Record count
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get Applications by company id and repository type
      tags:
      - Company
  /api/v1/companies/{id}/repositories:
    get:
      description: Gets RepositoriesDto by company id
      parameters:
      - description: Company id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get RepositoriesDto by company id
      tags:
      - Company
    put:
      description: updates repositories
      parameters:
      - description: List Of Repositories data
        in: body
        name: data
        required: true
        schema:
          type: object
      - description: Company id
        in: path
        name: id
        required: true
        type: string
      - description: Company Update Option
        in: query
        name: companyUpdateOption
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Update repositories by company id
      tags:
      - Company
  /api/v1/githubs/branches:
    get:
      description: Gets Branches
      parameters:
      - description: User Name
        in: query
        name: userName
        required: true
        type: string
      - description: Repository Id
        in: query
        name: repoId
        required: true
        type: string
      - description: Repository Name
        in: query
        name: repoName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get Branches
      tags:
      - Github
  /api/v1/githubs/commits:
    get:
      description: Gets commit by branch
      parameters:
      - description: User Name
        in: query
        name: userName
        required: true
        type: string
      - description: branch
        in: query
        name: branch
        required: true
        type: string
      - description: Repository Id
        in: query
        name: repoId
        required: true
        type: string
      - description: Repository Name
        in: query
        name: repoName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get commit by branch
      tags:
      - Github
  /api/v1/githubs/webhooks:
    delete:
      description: Disable Webhook
      parameters:
      - description: User Name
        in: query
        name: userName
        required: true
        type: string
      - description: Repository Id
        in: query
        name: repoId
        required: true
        type: string
      - description: Repository Name
        in: query
        name: repoName
        required: true
        type: string
      - description: Webhook Id
        in: query
        name: webhookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Disable Webhook
      tags:
      - Github
    put:
      description: Enable Webhook
      parameters:
      - description: User Name
        in: query
        name: userName
        required: true
        type: string
      - description: Repository Id
        in: query
        name: repoId
        required: true
        type: string
      - description: Repository Name
        in: query
        name: repoName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Enable Webhook
      tags:
      - Github
  /api/v1/logs:
    post:
      consumes:
      - application/json
      description: Stores logs
      parameters:
      - description: LogEvent Data
        in: body
        name: data
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Save log
      tags:
      - Log
  /api/v1/pipelines/{processId}:
    get:
      description: Gets Pipeline or logs by pipeline processId [If action is "get_pipeline",
        then pipeline will be returned or logs will be returned. Available if local
        storage is enabled]
      parameters:
      - description: Pipeline ProcessId
        in: path
        name: processId
        required: true
        type: string
      - description: action
        in: query
        name: action
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Record count
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.ResponseDTO'
            - properties:
                data:
                  items:
                    type: string
                  type: array
              type: object
      summary: Get Pipeline or logs [available if local storage is enabled]
      tags:
      - Pipeline
  /api/v1/pipelines/ws:
    get:
      description: Get events by process id
      parameters:
      - description: process id
        in: query
        name: processId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get events by process id
      tags:
      - Pipeline
  /api/v1/process_life_cycle_events:
    get:
      description: Pulls auto trigger enabled steps
      parameters:
      - description: Agen name
        in: path
        name: agent
        required: true
        type: string
      - description: Pull size
        in: path
        name: count
        required: true
        type: integer
      - description: Step type [BUILD, DEPLOY]
        in: path
        name: step_type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Pull Steps
      tags:
      - ProcessLifeCycle
    post:
      consumes:
      - application/json
      description: Stores process lifecycle event
      parameters:
      - description: ProcessLifeCycleEventList Data
        in: body
        name: data
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Save process lifecycle event
      tags:
      - ProcessLifeCycle
  /api/v1/processes:
    get:
      description: Get Process List or count process
      parameters:
      - description: Repository Id
        in: query
        name: repositoryId
        type: string
      - description: App Id
        in: query
        name: appId
        type: string
      - description: Commit Id
        in: query
        name: commitId
        type: string
      - description: Operation[countTodaysProcessByCompanyId]
        in: query
        name: operation
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get Process List or count process
      tags:
      - Process
  /api/v1/processes_events:
    post:
      consumes:
      - application/json
      description: Stores Pipeline process event
      parameters:
      - description: PipelineProcessEvent Data
        in: body
        name: data
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Save Pipeline process event
      tags:
      - ProcessEvent
  /api/v1/repositories/{id}:
    get:
      description: Get repository by repository id
      parameters:
      - description: repository id
        in: path
        name: repositoryId
        required: true
        type: string
      - description: Load applications
        in: query
        name: loadApplications
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get repository by repository id
      tags:
      - Repository
  /api/v1/repositories/{id}/applications:
    get:
      description: Get applications by repository id
      parameters:
      - description: repository id
        in: path
        name: repositoryId
        required: true
        type: string
      - description: status
        in: query
        name: status
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Record count
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResponseDTO'
      summary: Get applications by repository id
      tags:
      - Repository
swagger: "2.0"
